version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME : user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: tasks
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://localhost:27017/tasks --quiet
      interval: 10s
      timeout: 10s
      retries: 5  

  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:80"
    env_file:
      - ./backend/.env
    depends_on:
      mongodb:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

volumes:
  mongodata: